### ISSUE TITLE
ClueWeb09 WARC files faile to parse

### ISSUE THREAD

**Issue by sebastian-nagel** [iipc/jwarc#26]
The [ClueWeb09](http://www.lemurproject.org/clueweb09/datasetInformation.php) dataset WARC files (see [sample files](http://www.lemurproject.org/clueweb09/sampleFiles.php)) use a single line feed `\n` as separator between WARC headers. The WarcParser expects `\r\n` (which would conform to the standard) and fails:
```
Exception in thread "main" org.netpreserve.jwarc.ParsingException: invalid WARC record at position 9: WARC/0.18<-- HERE -->\nWARC-Type: warcinfo\nWARC-Date: 2009-03-...
```

See also #25 for a similar issue regarding HttpParser.

**Comment by ato** [comment]
I've added a lenient parsing mode which accepts \n line endings and the WARC/0.18 version string.

The ClueWeb09 sample files are quite broken though. They also have incorrect Content-Length headers. My guess is the files originally had \r\n line endings but then had them stripped to \n. I don't see a straightforward way to recover from that during parsing.

**Comment by wumpus** [comment]
It would be nice to have some examples distributed adjacent to the WARC standard of "these are some known broken WARC files out in the wild, you might want to think about either parsing them or at least giving good error messages when you see them".
