### ISSUE TITLE
wget quirk: Content-Length off by one

### ISSUE THREAD

**Issue by ato** [iipc/jwarc#29]
Some versions of wget generated WARC headers with an off by one Content-Length. This causes us to throw:

    org.netpreserve.jwarc.ParsingException: invalid WARC trailer: a0d0a57

Examples:
* [http_message_1.warc.gz](https://github.com/iipc/jwarc/files/4326781/http_message_1.warc.gz) Wget/1.19.4 (from #25)
* [http_chunked_2.warc.gz](https://github.com/iipc/jwarc/files/4326760/http_chunked_2.warc.gz) Wget/1.19.4 (from #24)

Other implementations appear to ignore this error. Perhaps by simply skipping arbitrary numbers of CR and LF characters before reading the next record?

I don't want to silently ignore this but perhaps we could log a warning and attempt to continue.

**Comment by sebastian-nagel** [comment]
+1 to skip trailing empty lines, cf. [warcio's archiveiterator.py](https://github.com/webrecorder/warcio/blob/566722d2d600ab8a96f7cdd31705da40106bed6e/warcio/archiveiterator.py#L155). With per-record compressed WARC files the Content-Length is not really required for reading, it's more a validation feature, same as the digests.
