### ISSUE TITLE
Native OSX / Linux binaries do not work

### ISSUE THREAD

**Issue by ikreymer** [iipc/jwarc#61]
When using the native osx binary from the 0.16.1 release, it seems the binary does load, but the cmdline parsing is broken.
Getting an invalid command for every command, eg:
```
jwarc: 'validate' is not a jwarc command. See 'jwarc help'.
```

```
jwarc: 'help' is not a jwarc command. See 'jwarc help'.
```

I am using it on an arm64 mac, but that should be transparent (should automatically use the emulation).

**Comment by ikreymer** [comment]
Unfortunately, the same happened on an Ubuntu machine using the linux binary..

**Comment by ato** [comment]
Thanks for reporting this. Seems to have been a bug in GraalVM native-image as when I updated the build script to use the latest version of GraalVM it works now. At least the Linux one does anyway, I don't currently have a Mac to test the darwin binary on.

New binaries here:
https://github.com/iipc/jwarc/releases/tag/v0.16.4

**Comment by ikreymer** [comment]
Thanks! Confirmed the 0.16.4 binaries work on OSX as well!
