### ISSUE TITLE
Request/Response Builder with String targetURI

### ISSUE THREAD

**Issue by robertvanloenhout** [iipc/jwarc#63]
Please add a constructor in the WarcRequest.Builder and the WarcResponse.Builder that accepts a String instead of a URI class.
The internet is full of URI's that are difficult or impossible to parse to convert them to a URI class. Jwarc only calls targetURI.toString(), so this would be a small change.

**Comment by ato** [comment]
Feel free to submit a pull request with this change. :-)

**Comment by robertvanloenhout** [comment]
I have created a pull request at https://github.com/iipc/jwarc/pull/64
