### ISSUE TITLE
Build WarcRevisit with refersTo String targetURI

### ISSUE THREAD

**Issue by robertvanloenhout** [iipc/jwarc#65]
I'd like to be able to create a WarcRevisit with the builder. However the target URI can only be set using an object of class URI.
It would be very convenient if I could pass a String.
Converting between URI and String gives some unnecessary headaches. For example I sometimes get a double URL encoded value from WarcTargetRecord.targetURI.

I'll add a pull request for this.
https://github.com/iipc/jwarc/pull/66

**Comment by ato** [comment]
Resolved by #66 in v0.20.0.
