### ISSUE TITLE
WarcRevisit Builder with String targetURI

### ISSUE THREAD

**Issue by robertvanloenhout** [iipc/jwarc#67]
Similar to https://github.com/iipc/jwarc/issues/63 I have added an additional constructor to accept a String instead of an URI when building a WarcRevisit.
I'll add a pull request for this.
https://github.com/iipc/jwarc/pull/68

I would be grateful if this can become part of the jwarc library.

**Comment by ato** [comment]
Thanks. Released as 0.21.0
