### ISSUE TITLE
Multithreading issue on GzipChannel write header

### ISSUE THREAD

**Issue by creyer** [iipc/jwarc#79]
When having multiple instances of WarcWriter the operations on 
`private static final ByteBuffer GZIP_HEADER = ByteBuffer.wrap(GZIP_HEADER_);` are causing issues. 
Some threads are writing the gzip header, some might not.

I think the issue could be fixed by removing the `static` part for the GZIP_HEADER.

**Comment by ato** [comment]
Yikes. Good catch.

Suggested fix applied in 68575d42cf0c589b78923055864ab73640b5e78e and released as 0.28.3.
